export const PERMISSION_CATALOGUE = [
  ['product.view', 'View products and public product information.'],
  ['product.create', 'Create products.'],
  ['product.update', 'Update products.'],
  ['product.delete', 'Delete or archive products.'],
  ['category.view', 'View product categories.'],
  ['category.create', 'Create product categories.'],
  ['category.update', 'Update product categories.'],
  ['category.delete', 'Delete or archive product categories.'],
  ['inventory.view', 'View internal inventory records.'],
  ['inventory.quantity.view', 'View confidential inventory quantities.'],
  ['inventory.adjust', 'Adjust internal inventory.'],
  ['inventory.transaction.view', 'View inventory transaction history.'],
  ['inventory.reservation.view', 'View internal inventory reservations.'],
  ['inventory.reservation.create', 'Create internal inventory reservations.'],
  [
    'inventory.reservation.update',
    'Complete or update internal inventory reservations.',
  ],
  ['inventory.reservation.release', 'Release internal inventory reservations.'],
  [
    'inventory.reservation.override',
    'Record an intentional reservation shortfall override.',
  ],
  ['inventory.availability.view', 'View confidential date-range availability.'],
  ['rental_request.view', 'View rental requests.'],
  ['rental_request.assign', 'Assign rental requests.'],
  ['rental_request.update', 'Update rental requests.'],
  ['rental_request.approve', 'Approve rental requests.'],
  ['rental_request.partially_approve', 'Partially approve rental requests.'],
  ['rental_request.reject', 'Reject rental requests.'],
  [
    'rental_request_revision.view',
    'View immutable rental request revisions and comparisons.',
  ],
  ['rental_request_amendment.view', 'View customer rental request amendments.'],
  [
    'rental_request_amendment.review',
    'Start and complete amendment re-review.',
  ],
  ['rental_change_request.view', 'View formal customer change requests.'],
  ['rental_change_request.review', 'Review formal customer change requests.'],
  ['quote.view', 'View quotes.'],
  ['quote.create', 'Create quotes.'],
  ['quote.update', 'Update quotes.'],
  ['quote.send', 'Send quotes to customers.'],
  ['quote.approve', 'Approve protected quote actions.'],
  ['order.view', 'View confirmed rental orders.'],
  ['order.create', 'Create confirmed rental orders.'],
  ['order.update', 'Update confirmed rental orders.'],
  ['fulfilment.view', 'View internal fulfilment preparation and checkout.'],
  ['fulfilment.prepare', 'Prepare reserved equipment for fulfilment.'],
  ['fulfilment.checkout', 'Check reserved equipment out to a customer.'],
  ['fulfilment.partial_checkout', 'Authorise intentional partial checkout.'],
  ['fulfilment.handoff', 'Confirm pickup or delivery handoff.'],
  ['fulfilment.pdf', 'Download internal fulfilment documents.'],
  ['active_rental.view', 'View active rental records.'],
  ['return.view', 'View internal rental return records.'],
  ['return.create', 'Record equipment return intake.'],
  ['return.partial', 'Record intentional partial returns.'],
  ['return.inspect', 'Classify returned equipment condition.'],
  ['return.reconcile', 'Reconcile fully accounted rental returns.'],
  ['return.complete', 'Complete reconciled active rentals.'],
  ['return.pdf', 'Download internal return and reconciliation documents.'],
  ['rental_issue.view', 'View internal return issues.'],
  ['rental_issue.update', 'Create and update internal return issues.'],
  ['rental_issue.resolve', 'Resolve return issues and record recoveries.'],
  ['maintenance.view', 'View internal maintenance work orders.'],
  ['maintenance.create', 'Create internal maintenance work orders.'],
  ['maintenance.assign', 'Assign maintenance work to active staff.'],
  ['maintenance.update', 'Update active maintenance work orders.'],
  ['maintenance.complete', 'Complete maintenance work orders.'],
  ['maintenance.cancel', 'Cancel active maintenance work orders.'],
  ['maintenance.note', 'Add internal maintenance notes.'],
  [
    'maintenance.inventory_transition',
    'Move equipment into or out of maintenance through an authorised workflow.',
  ],
  ['inspection.view', 'View internal equipment inspections.'],
  ['inspection.create', 'Schedule internal equipment inspections.'],
  ['inspection.perform', 'Perform and record equipment inspections.'],
  ['inspection.cancel', 'Cancel scheduled equipment inspections.'],
  ['customer.view', 'View customer records needed for staff work.'],
  ['customer.update', 'Update customer records.'],
  ['user.view', 'View staff users.'],
  ['user.create', 'Create staff users.'],
  ['user.update', 'Update staff users.'],
  ['user.delete', 'Delete or archive staff users.'],
  ['user.role.manage', 'Assign and remove staff roles.'],
  ['role.view', 'View roles and the permission catalogue.'],
  ['role.create', 'Create custom roles.'],
  ['role.update', 'Update custom role metadata.'],
  ['role.delete', 'Delete or archive custom roles.'],
  ['role.manage_permissions', 'Change role-to-permission assignments.'],
  [
    'role.super_admin.manage',
    'Assign or remove the protected SUPER_ADMIN role.',
  ],
  ['content.view', 'View website content.'],
  ['content.create', 'Create website content.'],
  ['content.update', 'Update website content.'],
  ['content.delete', 'Delete or archive website content.'],
  ['homepage.view', 'View homepage drafts and publication history.'],
  ['homepage.edit', 'Create and edit homepage drafts.'],
  ['homepage.publish', 'Publish or restore homepage revisions.'],
  ['homepage.media.manage', 'Upload and remove homepage media.'],
  ['homepage.preview', 'Preview unpublished homepage revisions.'],
  [
    'homepage.google_reviews.view_status',
    'View the Google Reviews integration configuration status.',
  ],
  ['report.view', 'View protected reports.'],
  ['report.export', 'Export bounded protected report data.'],
  ['audit_log.view', 'View audit logs.'],
  ['audit_log.export', 'Export bounded audit-history data.'],
  ['observability.view', 'View protected operational system status.'],
  ['backup.view_status', 'View protected backup verification status.'],
  ['feature_settings.view', 'View operational feature controls.'],
  ['feature_settings.manage', 'Manage operational feature controls.'],
  ['contact_enquiry.view', 'View customer contact enquiries.'],
  ['contact_enquiry.manage', 'Update customer contact enquiry status.'],
  ['public_pages.view', 'View public page drafts and revision history.'],
  ['public_pages.edit', 'Create and edit structured public page drafts.'],
  ['public_pages.publish', 'Publish or restore public page revisions.'],
] as const;

export type PermissionKey = (typeof PERMISSION_CATALOGUE)[number][0];
export const ALL_PERMISSION_KEYS = PERMISSION_CATALOGUE.map(([key]) => key);

export const SYSTEM_ROLES = [
  {
    description: 'Protected owner-level role with every seeded permission.',
    displayName: 'Super Admin',
    name: 'SUPER_ADMIN',
  },
  {
    description:
      'Broad operational administration without owner-only RBAC powers.',
    displayName: 'Admin',
    name: 'ADMIN',
  },
  {
    description: 'Public product, category, and website content management.',
    displayName: 'Editor',
    name: 'EDITOR',
  },
  {
    description: 'Customer rental-request and quotation sales workflows.',
    displayName: 'Sales Person',
    name: 'SALES_PERSON',
  },
] as const;

export type SystemRoleName = (typeof SYSTEM_ROLES)[number]['name'];

const ADMIN_PERMISSIONS = [
  'product.view',
  'product.create',
  'product.update',
  'product.delete',
  'category.view',
  'category.create',
  'category.update',
  'category.delete',
  'inventory.view',
  'inventory.quantity.view',
  'inventory.adjust',
  'inventory.transaction.view',
  'inventory.reservation.view',
  'inventory.reservation.create',
  'inventory.reservation.update',
  'inventory.reservation.release',
  'inventory.reservation.override',
  'inventory.availability.view',
  'rental_request.view',
  'rental_request.assign',
  'rental_request.update',
  'rental_request.approve',
  'rental_request.partially_approve',
  'rental_request.reject',
  'rental_request_revision.view',
  'rental_request_amendment.view',
  'rental_request_amendment.review',
  'rental_change_request.view',
  'rental_change_request.review',
  'quote.view',
  'quote.create',
  'quote.update',
  'quote.send',
  'quote.approve',
  'order.view',
  'order.create',
  'order.update',
  'fulfilment.view',
  'fulfilment.prepare',
  'fulfilment.checkout',
  'fulfilment.partial_checkout',
  'fulfilment.handoff',
  'fulfilment.pdf',
  'active_rental.view',
  'return.view',
  'return.create',
  'return.partial',
  'return.inspect',
  'return.reconcile',
  'return.complete',
  'return.pdf',
  'rental_issue.view',
  'rental_issue.update',
  'rental_issue.resolve',
  'maintenance.view',
  'maintenance.create',
  'maintenance.assign',
  'maintenance.update',
  'maintenance.complete',
  'maintenance.cancel',
  'maintenance.note',
  'maintenance.inventory_transition',
  'inspection.view',
  'inspection.create',
  'inspection.perform',
  'inspection.cancel',
  'customer.view',
  'customer.update',
  'user.view',
  'user.create',
  'user.update',
  'role.view',
  'content.view',
  'content.create',
  'content.update',
  'content.delete',
  'homepage.view',
  'homepage.edit',
  'homepage.publish',
  'homepage.media.manage',
  'homepage.preview',
  'homepage.google_reviews.view_status',
  'report.view',
  'report.export',
  'audit_log.view',
  'audit_log.export',
  'observability.view',
  'backup.view_status',
  'feature_settings.view',
  'feature_settings.manage',
  'contact_enquiry.view',
  'contact_enquiry.manage',
  'public_pages.view',
  'public_pages.edit',
  'public_pages.publish',
] as const satisfies readonly PermissionKey[];

const EDITOR_PERMISSIONS = [
  'product.view',
  'product.create',
  'product.update',
  'category.view',
  'category.create',
  'category.update',
  'content.view',
  'content.create',
  'content.update',
  'content.delete',
  'homepage.view',
  'homepage.edit',
  'homepage.publish',
  'homepage.media.manage',
  'homepage.preview',
  'homepage.google_reviews.view_status',
  'public_pages.view',
  'public_pages.edit',
  'public_pages.publish',
] as const satisfies readonly PermissionKey[];

const SALES_PERSON_PERMISSIONS = [
  'product.view',
  'category.view',
  'inventory.view',
  'inventory.quantity.view',
  'rental_request.view',
  'rental_request.assign',
  'rental_request.update',
  'rental_request_revision.view',
  'rental_request_amendment.view',
  'rental_request_amendment.review',
  'rental_change_request.view',
  'rental_change_request.review',
  'quote.view',
  'quote.create',
  'quote.update',
  'quote.send',
  'customer.view',
  'customer.update',
  'fulfilment.view',
  'return.view',
  'contact_enquiry.view',
  'contact_enquiry.manage',
] as const satisfies readonly PermissionKey[];

export const DEFAULT_ROLE_PERMISSION_KEYS = {
  ADMIN: ADMIN_PERMISSIONS,
  EDITOR: EDITOR_PERMISSIONS,
  SALES_PERSON: SALES_PERSON_PERMISSIONS,
  SUPER_ADMIN: ALL_PERMISSION_KEYS,
} satisfies Record<SystemRoleName, readonly PermissionKey[]>;

export const SUPER_ADMIN_ROLE_NAME = 'SUPER_ADMIN' as const;
export const SUPER_ADMIN_MANAGE_PERMISSION = 'role.super_admin.manage' as const;

export function isPermissionKey(value: string): value is PermissionKey {
  return (ALL_PERMISSION_KEYS as readonly string[]).includes(value);
}
